### PR TITLE
Updated UI

### PR DESCRIPTION
**Pull request by vizvarun**

### CODE REVIEW

**Review by ayulockin — COMMENTED** [review]
I see that you created a separate folder and did the changes there. 
Please make the changes on the main file. I understand you did this to retain the original copy of the forked repo. But since the PR is not yet merged into the master branch you always have a copy. 

I suggest to make the changes in the main files..and remove `Updated` folder. This looks really amazing.

**Comment by ayulockin** [comment]
Screenshot (308)

You see when I opened it in my tab it's not fitting in the screen. Once I went full screen (Fn+F11) the true glory of Vison can be seen.

**Comment by ayulockin** [comment]
The location icon and location ain't aligned. It shouldn't be up and down. 

Screenshot (309)

**Comment by ayulockin** [comment]
Can the search bar be reduced in length. And cursor blink on the left hand side and not center. 
Reduce the length of the search bar and adjust every icon accordingly. This would look pleasing maybe.

**Comment by ayulockin** [comment]
@varunvishal10 You can take note of the comments and commit accordingly. <3

**Comment by vizvarun** [comment]
okay

**Comment by kasturi14** [comment]
The contents should fit the screen and the vertical scroll should be disabled.

**Comment by ayulockin** [comment]
Are the changes made @varunvishal10 ?

**Comment by vizvarun** [comment]
please merge till now, then everyone will be able to solve the issues

**Comment by ayulockin** [comment]
Okay I am merging this. A lot is yet to be done.

By the way great work @varunvishal10.

**Pull request merged**
